// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzc-gwWY5CzqE9Qw-0yTa-OzqAgY5E478',
    appId: '1:1034167010329:web:f088db07770747824ad688',
    messagingSenderId: '1034167010329',
    projectId: 'sensory-wardrobe',
    authDomain: 'sensory-wardrobe.firebaseapp.com',
    storageBucket: 'sensory-wardrobe.firebasestorage.app',
    measurementId: 'G-K0FB9SQTZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ZIos6sVi47mnGSq0cDcfdOxrmzBixXE',
    appId: '1:1034167010329:android:732dd7fba6421b004ad688',
    messagingSenderId: '1034167010329',
    projectId: 'sensory-wardrobe',
    storageBucket: 'sensory-wardrobe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzc-gwWY5CzqE9Qw-0yTa-OzqAgY5E478',
    appId: '1:1034167010329:web:9ddfc4cdb8d88e084ad688',
    messagingSenderId: '1034167010329',
    projectId: 'sensory-wardrobe',
    authDomain: 'sensory-wardrobe.firebaseapp.com',
    storageBucket: 'sensory-wardrobe.firebasestorage.app',
    measurementId: 'G-VTZKD6SFVN',
  );
}
